---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-egress

resources:
  - ocirepository.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: istio-egressgateway-values
    namespace: istio-egress
    files:
      - values.yaml=./values.yaml

configurations:
  - kustomizeconfig.yaml
