---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: external-dns-cloudflare
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        CERT_MANAGER_CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare-api-token 