---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - grafanadashboard.yaml  # Disabled - requires GrafanaDashboard CRD from grafana-operator
  - helmrelease.yaml
  - ocirepository.yaml
  - prometheusrule.yaml

configMapGenerator:
  - name: cert-manager-values
    namespace: network-system
    files:
      - values.yaml=./values.yaml

configurations:
  - kustomizeconfig.yaml
