---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafanadashboard.yaml
  - helmrelease.yaml
  - ocirepository.yaml

configMapGenerator:
  - name: cert-manager-values
    namespace: network-system
    files:
      - values.yaml=./values.yaml

configurations:
  - kustomizeconfig.yaml
