apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: arc-systems
spec:
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller
  interval: 5m
  secretRef:
    name: ghcr-auth