---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: "./kubernetes/apps/base/observability/oauth2-proxy/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-stores
    - name: istiod
  targetNamespace: observability
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
      - kind: ConfigMap
        name: workload-identity-config
        optional: true
