---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-egressgateway
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  path: "./kubernetes/apps/base/istio-egress/gateway/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: istio-egress
  dependsOn:
    - name: istiod
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istio-egressgateway
      namespace: istio-egress
