---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-secret: "{{ .client_secret }}"
        cookie-secret: "{{ .cookie_secret }}"
  data:
    - secretKey: client_secret
      remoteRef:
        key: oauth2-proxy-client-secret
    - secretKey: cookie_secret
      remoteRef:
        key: oauth2-proxy-cookie-secret
