apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: github-pat
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: github_token
      remoteRef:
        key: gh-flux-aks-token