apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
  labels:
    app.kubernetes.io/part-of: actions-runner-system
spec:
  provider:
    azurekv:
      vaultUrl: https://kv-myaks-tst-swn-00.vault.azure.net
      tenantId: 01b41838-a123-48a9-9aaf-91a8d640ff68
      authType: WorkloadIdentity


# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: azure-keyvault-store
#   namespace: actions-runner-system
# spec:
#   provider:
#     azurekv:
#       tenantId: "01b41838-a123-48a9-9aaf-91a8d640ff68"
#       vaultUrl: "https://kv-myaks-tst-swn-00.vault.azure.net/"
#       authType: WorkloadIdentity
#       serviceAccountRef:
#         name: external-secrets