---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
  annotations:
    external-dns.alpha.kubernetes.io/external: "true"
spec:
  gatewayClassName: istio
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.${CLUSTER_DOMAIN}"
      external-dns.alpha.kubernetes.io/external: "true"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      service.beta.kubernetes.io/port_80_health-probe_protocol: Tcp
      service.beta.kubernetes.io/port_443_health-probe_protocol: Tcp
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: "*.${CLUSTER_DOMAIN}"
      allowedRoutes:
        namespaces:
          from: All
    - name: https-wildcard
      port: 443
      protocol: HTTPS
      hostname: "*.${CLUSTER_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-tls-secret
            namespace: network-system
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: "true"
    - name: https-root
      port: 443
      protocol: HTTPS
      hostname: "${CLUSTER_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-tls-secret
            namespace: network-system
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: "true"
