---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-gateway-config
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: "./kubernetes/apps/base/istio-ingress/config"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: istio-ingress
  dependsOn:
    - name: istio-ingressgateway
    - name: cert-manager-certificates
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
