---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: # Istio intends to make Kubernetes Gateway API the default API for traffic management in the future.
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml
