---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: private-email
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault-store
  target:
    name: private-email
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        PRIVATE_EMAIL: "{{ .PRIVATE_EMAIL }}" 
  data:
    - secretKey: PRIVATE_EMAIL
      remoteRef:
        key: private-email-address