---
provider:
  name: cloudflare
domainFilters:
  - "${CLUSTER_DOMAIN}"
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare
        key: CLOUDFLARE_API_TOKEN
extraArgs:
  - --provider=cloudflare
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --annotation-filter=external-dns.alpha.kubernetes.io/external=true
policy: sync
txtPrefix: k8s.
sources:
  - crd
  # - gateway-httproute
serviceMonitor:
  enabled: true