apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-runner-scale-set-controller
  annotations:
    azure.workload.identity/client-id: "${AZURE_RUNNER_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"