---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - grafanadashboard.yaml  # Disabled - requires GrafanaDashboard CRD from grafana-operator
  - helmrelease.yaml
  - ocirepository.yaml
