---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  namespaceSelector:
    matchLabels:
      secrets.external-secrets.io/cloudflare: "true"
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: azure-keyvault-store
    target:
      name: cloudflare-api-token
      creationPolicy: Owner
      template:
        type: Opaque
        data:
          CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
    data:
      - secretKey: CLOUDFLARE_API_TOKEN
        remoteRef:
          key: cloudflare-api-token
