apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-global
spec:
  provider:
    azurekv:
      vaultUrl: https://kv-myaks-dev-swn-003.vault.azure.net
      authType: WorkloadIdentity