---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - actions-runner-controller.yaml
  - external-dns-chart.yaml
  - jetstack-charts.yaml
  - grafana-charts.yaml
