apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    app.kubernetes.io/name: external-secrets
    toolkit.fluxcd.io/tenant: platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
  labels:
    app.kubernetes.io/name: actions-runner-controller
    toolkit.fluxcd.io/tenant: platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
  labels:
    app.kubernetes.io/name: actions-runner-system
    app.kubernetes.io/part-of: github-runners
    toolkit.fluxcd.io/tenant: workload
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline