apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/action-runner-system

patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: aks-runners
      spec:
        values:
          minRunners: 0
          maxRunners: 5
    target:
      kind: HelmRelease
      name: aks-runners
      namespace: actions-runner-system