apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/action-runner-system

patches:
  - target:
      kind: HelmRelease
      name: aks-runners
    patch: |-
      - op: replace
        path: /spec/values/minRunners
        value: 0
      - op: replace
        path: /spec/values/maxRunners
        value: 5