---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: observability
  annotations:
    external-dns.alpha.kubernetes.io/external: "true"
    external-dns.alpha.kubernetes.io/hostname: "grafana.${CLUSTER_DOMAIN}"
spec:
  parentRefs:
    - name: istio-ingressgateway
      namespace: istio-ingress
      sectionName: https-grafana
  hostnames:
    - "grafana.${CLUSTER_DOMAIN}"
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/health
      backendRefs:
        - name: grafana-service
          namespace: observability
          port: 3000
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana-service
          namespace: observability
          port: 3000
      timeouts:
        request: 60s
        backendRequest: 55s
