---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-routes
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: "./kubernetes/apps/base/observability/routes"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  dependsOn:
    - name: istio-gateway-config
    - name: kube-prometheus-stack
    - name: grafana
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
