---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - grafana-httproute.yaml
  - prometheus-httproute.yaml
  - kiali-httproute.yaml
  - oauth2-proxy-httproute.yaml
