---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: observability
  annotations:
    external-dns.alpha.kubernetes.io/external: "true"
    external-dns.alpha.kubernetes.io/hostname: "prometheus.${CLUSTER_DOMAIN}"
spec:
  parentRefs:
    - name: istio-ingressgateway
      namespace: istio-ingress
      sectionName: https-prometheus
  hostnames:
    - "prometheus.${CLUSTER_DOMAIN}"
  rules:
    - matches:
        - path:
            type: Exact
            value: /-/healthy
      backendRefs:
        - name: kube-prometheus-stack-prometheus
          namespace: observability
          port: 9090
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kube-prometheus-stack-prometheus
          namespace: observability
          port: 9090
      timeouts:
        request: 120s
        backendRequest: 115s
