---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-config
data:
  CLUSTER_ID: 'aks-myaks-tst-swn-00'
  CLUSTER_DOMAIN: 'bjjeire.com'
  KEY_VAULT_NAME: "kv-myaks-test-swn-00"
  TENANT_ID: "01b41838-a123-48a9-9aaf-91a8d640ff68"
