---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/external-secrets/charts
  interval: 12h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
  interval: 12h
---