apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml 
- ../../apps
- ./arc-controller-namespace.yaml
- ./arc-controller-hr.yaml
