apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- external-secrets-operator.yaml
- ../../apps
- ./arc-controller-namespace.yaml
- ./arc-controller-hr.yaml
