apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: arc-systems
spec:
  type: oci
  url: oci://ghcr.io/actions-runner-controller/actions-runner-controller
  interval: 3m
  secretRef:
    name: ghcr-auth