apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: actions-runner-system
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-myaks-dev-swn-003.vault.azure.net"
      serviceAccountRef:
        name: actions-runner-controller-manager