apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: actions-runner-system
  annotations:
    azure.workload.identity/client-id: "${AZURE_RUNNER_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"
  labels:
    azure.workload.identity/use: "true"